### ISSUE TITLE
Use object-oriented matplotlib API

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-matplotlib#48]
Let's move examples and exercises of the module to an object-oriented approach. 

Currently, the module uses the pyplot interface:
```
import matplotlib.pyplot as plt

plt.title("First look at samples")
plt.hist(branches['data_A']['m4l'])
```

The object-oriented interface gives more control when we create figures that contain multiple plots, and it is recommended even for beginners. For example:
```
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1)
ax.plot(x, y)
ax.set_xlabel("x")
ax.set_ylabel("y")
```

Originally proposed by Thomas Caswell. And a nice post about the motivation behind:
https://danielmuellerkomorowska.com/2020/07/05/matplotlib-and-the-object-oriented-interface/

**Comment by klieret** [comment]
(I think the  `(1)` in `subplots` is superfluous, right?)

**Comment by michmx** [comment]
Oh right, not needed.

**Comment by Marchela04** [comment]
In chapter 4 there was an example using OO interface, if everything is going to be changed, please remove the line "In order to do this, we will use the subplot function. Notice that in this case, we are creating a figure and defining the axes of the figure directly, the syntax of the functions that we call for these axes change a bit with respect to the ones using only pyplot."

**Comment by klieret** [comment]
Thanks for the hint @Marchela04 I've checked and Wouter removed it :)

**Comment by klieret** [comment]
This is actually not done yet, see [this search](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fhsf-training%2Fhsf-training-matplotlib%24+%28plt.plot+or+plt.hist+or+plt.errorbar+or+plt.yticks%29&patternType=standard). I'll open separate issues for the different episodes.
