### ISSUE TITLE
Add Bonus Exercise to reproduce the Higgs Branching Ratio vs Higgs Mass plot.

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#81]
This issue is in reference to the plot in episode 3:   Branching Ratio(s) vs Higgs Mass

(Link https://hsf-training.github.io/hsf-training-matplotlib/03-physics/index.html#:~:text=hadron%20collider%20are-,The%20Higgs%20boson,-can%20decay%20into)

**Comment by klieret** [comment]
Good idea, but I'm a bit wary about adding more datasets to the lesson if not needed (because it shifts complexity towards loading data or understanding datasets rather than the actual *plotting*)

Also, from a learning-matplotlib perspective, what would be the benefit? It seems that this would probably be several `ax.plot` calls, right? 

But I'm not at all against adding it as an expandible/foldable box for students who are interested in it. Though I wouldn't put much priority on it.

**Comment by amorenobr** [comment]
Actually, I was thinking on doing the same... :) something simple without introducing new datasets, just trying to use (and keep practicing) what they learn in the introduction section. This could be something similar to the Feynman diagrams, show the plot and then a hidden section with an example. The idea is always to show all the possibilities that you can have using matplotlib, and also, since this is a matplotlib training, I think it would be interesting to show that all the plots were obtained using matplotlib... :)

**Comment by amanmdesai** [comment]
Hi @amorenobr , @klieret , my idea was to use the formula of Higgs decay width and try to generate the plots of branching ratios. The formulas can be found in any particle physics book and are valid at the tree level. It does not involve using any dataset. 

 But there seems to be some complexity involved and I am not so far successful in finding the answer.  Complexity is related to the H->VV decay as atleast one of the V (W/Z) has to be virtual at Mh = 125 GeV. 

Please check here: https://github.com/amanmdesai/Higgs-Physics for some development. I am happy to take your suggestions. Code looks a bit complex now, but I think we can try to make it more simple once we get acceptable results. 


Perhaps we could add a miscellaneous episode at the end containing such famous hep plots and how they can be made using matplotlib.

**Comment by klieret** [comment]
My intuition here is still that this is a bit out of the scope of the training itself. I'd also consider the Feynman diagrams a bit of a bonus, but there at least it's really centered on the _plotting_ and shows to what lengths matplotlib can be used. 

But in this example, the plotting itself is the trivial bit and the physics and generation of the curves is difficult. 

And even if we add it to the bonus part at the end, any kind of code needs to be maintained in some way and we might need to offer help to students who try their hands on it, so we need to conserve knowledge. 

So that's why I'm personally hesitant here.

**However**: We can also always add a callout box pointing them to your repository. Something like "If you're curious how to reproduce this plot, take a look at https://github.com/amanmdesai/Higgs-Physics". What do you think?

**Comment by amanmdesai** [comment]
Sounds good @klieret.  

I am still working on my repository. Perhaps I will reopen this issue when I am done with the plots/code and we could add/discuss the link then?

Thanks very much @klieret  and @amorenobr  for the discussions.

**Comment by klieret** [comment]
> I am still working on my repository. Perhaps I will reopen this issue when I am done with the plots/code and we could add/discuss the link then?

Sure :)
